Repository manicminer/hamilton, pull requests merged in 2021-06, with the labels that each got.

#54 Delete permanently API for apps, groups, and users
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/groups.go
  msgraph/users.go
  msgraph/users_test.go
Labels: enhancement

#55 NamedLocations: Set OData types in UpdateCountry / UpdateIP functions
  msgraph/namedlocations.go
Labels: bug

#56 Named locations add generic get
  msgraph/namedlocations.go
  msgraph/namedlocations_test.go
Labels: enhancement

#57 Implementation for retrying requests
  example/example.go
  go.mod
  go.sum
  msgraph/app_role_assignments.go
  msgraph/applications.go
  msgraph/client.go
  msgraph/conditionalaccesspolicy.go
  msgraph/directory_role_templates.go
  msgraph/directory_roles.go
  msgraph/domains.go
  msgraph/groups.go
  msgraph/identity_providers.go
  msgraph/namedlocations.go
  msgraph/serviceprincipals.go
  msgraph/users.go
  odata/odata.go
Labels: enhancement

#58 Restore deleted API for apps, groups, and users
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/groups.go
  msgraph/users.go
  msgraph/users_test.go
Labels: enhancement

#59 Add new type alias StringNullWhenEmpty for nullable string values
  msgraph/models.go
  msgraph/valuetypes.go
Labels: breaking change, enhancement

#61 Add Support For Sign-in,Directory Audit get/list actions and Create/List/Delete for Application Extensions
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/directory_audit_reports.go
  msgraph/directory_audit_reports_test.go
  msgraph/models.go
  msgraph/sign_in_reports.go
  msgraph/sign_in_reports_test.go
  msgraph/valuetypes.go
Labels: enhancement

#63 Support OData queries
  README.md
  aadgraph/client.go
  example/example.go
  internal/utils/pointers.go
  msgraph/app_role_assignments_test.go
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/client.go
  msgraph/conditionalaccesspolicy.go
  msgraph/conditionalaccesspolicy_test.go
  msgraph/directory_audit_reports.go
  msgraph/directory_audit_reports_test.go
  msgraph/directory_roles.go
  msgraph/groups.go
  msgraph/groups_test.go
  msgraph/identity_providers_test.go
  msgraph/namedlocations.go
  msgraph/namedlocations_test.go
  msgraph/serviceprincipals.go
  msgraph/serviceprincipals_test.go
  msgraph/sign_in_reports.go
  msgraph/sign_in_reports_test.go
  msgraph/users.go
  msgraph/users_test.go
  odata/query.go
  odata/query_test.go
Labels: breaking change, enhancement

#64 Test coverage for 365 groups, including undeletion and permanent deletion
  msgraph/groups.go
  msgraph/groups_test.go
Labels: tests

#66 Don't remove all role assignments during test, target 'Global Reader' role for safety
  msgraph/directory_role_templates_test.go
  msgraph/directory_roles_test.go
Labels: bug, tests

#65 Enable passing in the raw bytes of a PKCS#12 bundle when constructing a client certificate authorizer
  auth/auth.go
  auth/auth_test.go
  auth/config.go
  internal/test/msi_stub.go
  internal/test/testing.go
Labels: breaking change, enhancement

#67 Run tests with GitHub Actions
  .github/workflows/auth-tests.yml
  .github/workflows/golint.yml
  .github/workflows/msgraph-tests.yml
  .github/workflows/odata-tests.yml
  .github/workflows/scheduled-cleanup.yml
  auth/auth.go
  auth/auth_test.go
  environments/published.go
  internal/cmd/test-cleanup/applications.go
  internal/cmd/test-cleanup/conditionalaccesspolicies.go
  internal/cmd/test-cleanup/groups.go
  internal/cmd/test-cleanup/main.go
  internal/cmd/test-cleanup/namedlocations.go
  internal/cmd/test-cleanup/serviceprincipals.go
  internal/cmd/test-cleanup/users.go
  internal/test/msi_stub.go
  internal/test/testing.go
  internal/utils/base64.go
  msgraph/app_role_assignments_test.go
  msgraph/conditionalaccesspolicy_test.go
  msgraph/directory_role_templates_test.go
  msgraph/directory_roles_test.go
  msgraph/groups_test.go
  msgraph/identity_providers_test.go
  msgraph/invitations_test.go
  msgraph/models.go
  msgraph/namedlocations_test.go
  msgraph/serviceprincipals_test.go
  msgraph/users_test.go
  odata/odata.go
  odata/odata_test.go
Labels: tests

#71 Rework GitHub workflows
  .github/workflows/auth-tests.yml
  .github/workflows/golint.yml
  .github/workflows/msgraph-tests.yml
  .github/workflows/odata-tests.yml
Labels: tests

#68 Add Support For Schema Extensions
  msgraph/models.go
  msgraph/schema_extensions.go
  msgraph/schema_extensions_test.go
  msgraph/valuetypes.go
Labels: enhancement

#72 Extend User model - Add SignInActivity
  msgraph/models.go
Labels: enhancement

#74 Support `spa` property for applications
  msgraph/models.go
Labels: enhancement
