Repository manicminer/hamilton, pull requests merged in 2021-04, with the labels that each got.

#22 AppID for Domain Controller Services
  environments/published.go
Labels: enhancement

#23 API Support for Conditional Access Policy
  msgraph/conditionalaccesspolicy.go
  msgraph/conditionalaccesspolicy_test.go
  msgraph/models.go
Labels: enhancement

#27 API support for directory role templates
  .gitignore
  msgraph/directory_role_templates.go
  msgraph/directory_role_templates_test.go
  msgraph/models.go
Labels: enhancement

#28 Improve error handling, skip broken test, set a default user agent
  aadgraph/applicationrefs_test.go
  msgraph/applications.go
  msgraph/client.go
  msgraph/conditionalaccesspolicy.go
  msgraph/directory_role_templates.go
  msgraph/domains.go
  msgraph/groups.go
  msgraph/invitation.go
  msgraph/me.go
  msgraph/serviceprincipals.go
  msgraph/users.go
Labels: enhancement, tests

#24 Add IP and Country Named Locations
  msgraph/models.go
  msgraph/namedlocations.go
  msgraph/namedlocations_test.go
Labels: enhancement

#30 Add support for directory role
  msgraph/directory_role_templates_test.go
  msgraph/directory_roles.go
  msgraph/directory_roles_test.go
  msgraph/models.go
Labels: enhancement, tests

#35 Bugfixes and improvements
  aadgraph/client.go
  auth/clientcredentials.go
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/client.go
  msgraph/groups.go
  msgraph/invitations.go
  msgraph/models.go
  msgraph/namedlocations.go
  msgraph/serviceprincipals.go
  odata/odata.go
Labels: breaking change, bug, enhancement

#31 Add support for directory role activation
  msgraph/applications.go
  msgraph/directory_role_templates_test.go
  msgraph/directory_roles.go
  msgraph/groups.go
  msgraph/serviceprincipals.go
  odata/odata.go
Labels: enhancement

#32 Add support for app role assignments to groups
  msgraph/app_role_assignments.go
  msgraph/app_role_assignments_test.go
  msgraph/models.go
Labels: enhancement
