Repository manicminer/hamilton, pull requests merged in 2021-08, with the labels that each got.

#85 Add Support for Identity Registration and Usage Reports
  go.mod
  go.sum
  msgraph/models.go
  msgraph/reports.go
  msgraph/reports_test.go
  msgraph/sign_in_reports_test.go
  msgraph/valuetypes.go
Labels: enhancement

#88 Cache access tokens from Azure CLI
  auth/azcli.go
Labels: bug

#86 Support for generic directory objects and improved odata field handling
  msgraph/app_role_assignments.go
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/client.go
  msgraph/conditionalaccesspolicy.go
  msgraph/directory_audit_reports.go
  msgraph/directory_objects.go
  msgraph/directory_objects_test.go
  msgraph/directory_role_templates.go
  msgraph/directory_roles.go
  msgraph/directory_roles_test.go
  msgraph/domains.go
  msgraph/groups.go
  msgraph/groups_test.go
  msgraph/identity_providers.go
  msgraph/identity_providers_test.go
  msgraph/invitations.go
  msgraph/me.go
  msgraph/models.go
  msgraph/namedlocations.go
  msgraph/reports.go
  msgraph/schema_extensions.go
  msgraph/serviceprincipals.go
  msgraph/serviceprincipals_test.go
  msgraph/sign_in_reports.go
  msgraph/users.go
  msgraph/users_test.go
  msgraph/valuetypes.go
  odata/odata.go
Labels: enhancement

#89 Add Support For Authentication Methods endpoints
  msgraph/authentication_methods.go
  msgraph/authentication_methods_test.go
  msgraph/models.go
  msgraph/valuetypes.go
  odata/odata.go
Labels: enhancement

#90 Improve CachedAuthorizer
  auth/azcli.go
  auth/cache.go
  auth/clientcredentials.go
  auth/msi.go
Labels: enhancement, breaking change, package/auth
