Repository manicminer/hamilton, pull requests merged in 2021-05, with the labels that each got.

#37 add support for sending emails
  msgraph/me.go
  msgraph/models.go
  msgraph/users.go
Labels: enhancement

#43 Handle bad API responses when parsing OData errors
  go.sum
  odata/odata.go
Labels: bug

#45 Support adding/removing service principal passwords
  msgraph/applications_test.go
  msgraph/serviceprincipals.go
  msgraph/serviceprincipals_test.go
Labels: enhancement

#38 Owned objects API for service principal
  msgraph/serviceprincipals.go
  msgraph/serviceprincipals_test.go
Labels: enhancement

#41 add support for identity providers
  msgraph/identity_providers.go
  msgraph/identity_providers_test.go
  msgraph/models.go
Labels: enhancement

#49 Fix body marshalling for addPassword
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/serviceprincipals.go
  msgraph/serviceprincipals_test.go
Labels: bug

#39 add support for app role assignments for users, groups and sp
  msgraph/app_role_assignments.go
  msgraph/app_role_assignments_test.go
  msgraph/serviceprincipals.go
  msgraph/serviceprincipals_test.go
Labels: enhancement

#46 [WIP] Perform read lock to reduce race window for checking cached tokens
  auth/cache.go
Labels: bug

#48 List deleted API for apps, groups, and users
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/groups.go
  msgraph/models.go
  msgraph/users.go
  msgraph/users_test.go
Labels: enhancement

#51 Get deleted API for apps, groups, and users
  msgraph/applications.go
  msgraph/applications_test.go
  msgraph/groups.go
  msgraph/users.go
  msgraph/users_test.go
Labels: enhancement

#52 Improve groups test: add owners and members at create time, nil checks in GroupsClient
  msgraph/groups.go
  msgraph/groups_test.go
Labels: tests

#53 Bug fix: restore missing OnPremisesImmutableId field for User model
  msgraph/models.go
Labels: bug
