Repository manicminer/hamilton, pull requests merged in 2021-01, with the labels that each got.

#3 Test fixups and documentation updates
  CONTRIBUTING.md
  README.md
  auth/auth_test.go
  clients/groups_test.go
  clients/internal/testing.go
Labels: documentation

#4 Methods on models.ApplcationApi to manage Oauth2PermissionScopes
  models/applications.go
Labels: enhancement

#5 User: ListGroupMemberships
  auth/claims.go
  clients/users.go
  clients/users_test.go
Labels: enhancement

#7 OData pagination handling
  base/get.go
  base/odata.go
  clients/applications_test.go
  clients/groups_test.go
  clients/serviceprincipals_test.go
  clients/users_test.go
Labels: enhancement

#8 Service Principals: ListGroupMemberships
  clients/serviceprincipals.go
  clients/serviceprincipals_test.go
Labels: enhancement

#10 More testing for base/odata
  base/odata/odata_test.go
  clients/applications_test.go
  clients/groups_test.go
  clients/internal/testing.go
  clients/serviceprincipals_test.go
  clients/users_test.go
  internal/utils/pointers.go
Labels: tests

#11 Support MSI authentication, improve auth tests
  auth/auth.go
  auth/auth_test.go
  auth/msi.go
Labels: enhancement

#14 Azure CLI version check
  auth/azcli.go
  go.mod
  go.sum
Labels: enhancement

#15 Refactor auth package
  auth/auth.go
  auth/cache.go
  auth/clientcredentials.go
  auth/config.go
  auth/internal/microsoft/client_assertion.go
  auth/internal/microsoft/client_secret.go
  auth/internal/microsoft/config.go
  auth/internal/microsoft/token.go
  auth/msi.go
  go.mod
  go.sum
Labels: refactor

#17 Validate MSI configuration before returning an MsiAuthorizer, cap HTTP timeout to 10 seconds
  auth/auth.go
  auth/msi.go
Labels: enhancement
